### ISSUE TITLE
difference between this and LLVM 6.0 for Windows

### ISSUE THREAD

**Issue by ChrisChiasson** [martell/mingw-w64-clang#2]
Mr. Malone,
May I ask: Is this project's linker different than the normal [Clang for Windows 32 or 64 bit downloads](http://releases.llvm.org/download.html)? I ask because when I attempt to follow the normal Clang's [`clang++ -target x86_64-pc-windows-gnu` or `clang++ -target i686-pc-windows-gnu`](https://stackoverflow.com/questions/39871656/how-to-use-clang-with-mingw-w64-headers-on-windows) commands as shown on StackOverflow, I hit (different) linker errors, regardless of which linker I use. I would like to use lld. I have noticed I have to supply `-fuse-linker=lld.exe` in order to do so--it won't let me leave off `.exe`. Unlike the person who answered on StackOverflow who was linking a trivial executable, my attempt fails with `lld: error: unknown argument: --start-group`, which I assume involves an automatic command line argument that arises in more complicated cases. Sorry for opening an issue to ask this question.
Respectfully,
Chris

**Comment by ChrisChiasson** [comment]
Also, I wanted to add that I realize this repo may (or may not) be [intended to deal just with cross compiling from linux](https://github.com/mstorsjo/llvm-mingw/pull/2), rather than generating a windows native compiler.

**Comment by martell** [comment]
> Is this project's linker different than the normal Clang for Windows 32 or 64 bit downloads? I ask because when I attempt to follow the normal Clang's clang++ -target x86_64-pc-windows-gnu or clang++ -target i686-pc-windows-gnu commands as shown on StackOverflow, I hit (different) linker errors, regardless of which linker I use. I would like to use lld. I have noticed I have to supply -fuse-linker=lld.exe in order to do so--it won't let me leave off .exe. Unlike the person who answered on StackOverflow who was linking a trivial executable, my attempt fails with lld: error: unknown argument: --start-group, which I assume involves an automatic command line argument that arises in more complicated cases.

All the code to support the gnu flags were upstreamed into lld a few months ago. Since lld 6.0.0 `--start-group` is a valid flag and you can invoke the gnu ld frontend instead of the msvc frontend.
So there is no difference between this and upstream windows lld 6.0.0 package other then this was build by mingw-w64-clang itself instead of msvc. 

> Also, I wanted to add that I realize this repo may (or may not) be intended to deal just with cross compiling from linux, rather than generating a windows native compiler.

This project already bootstraps a native compiler.
It builds the toolchain for linux first then builds the mingw-w64 bits.
Then using that cross compiler it rebuilds itself which will run on windows natively.
I then test this using wine to emulate windows.

> Sorry for opening an issue to ask this question.

No problem, glad I can help.

**Comment by ChrisChiasson** [comment]
That is weird (I have LLVM 6 32 bit for Windows from the official site and
MinGW w64 GCC 32 bit posix dwarf from the MinGW builds sourceforge), I
wonder what is going on :/

**Comment by martell** [comment]
> That is weird (I have LLVM 6 32 bit for Windows from the official site and MinGW w64 GCC 32 bit posix dwarf from the MinGW builds sourceforge), I wonder what is going on :/

The mingw-w64 you use with lld must be built with clang and llvm-dlltool not gcc and binutils.
Specifically llvm-dlltool creates valid imports libs to use with lld or link.exe.
binutils dlltool uses a custom out of spec format that only binutils ld understands.

I have scripts to extract the final toolchain from this docker image and plan to start doing releases soon if you can't extract it yourself.

**Comment by ChrisChiasson** [comment]
On the other reports linked in my 2nd post, I was able to pull the files
out of the final image by docker running bash, tarring the "prefix"
directory (with the build artifacts), and, from another ssh session, docker
copying the tar out of the running container.  I will try that on yours if
I can get access to Alpine on Google compute engine's docker.

**Comment by ChrisChiasson** [comment]
Had some problems with the Alpine mirrors, but that cleared up. It built all day on google compute engine and only started to fail near the end when it tried to run the wine tests and couldn't acquire a display. Think it would be ok to try to log into the image and pull out the build, or do the last errors seem unrecoverable?
```
 ---> 5b2c644ba9f0
Removing intermediate container ebb8814d2213
Step 53/57 : RUN apk add --no-cache wine freetype
 ---> Running in b9addd1849ca
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/2) Installing libpng (1.6.34-r1)
(2/2) Installing freetype (2.8.1-r2)
OK: 640 MiB in 78 packages
 ---> bce0ffcf7d4c
Removing intermediate container b9addd1849ca
Step 54/57 : RUN WINEARCH=win64 winecfg
 ---> Running in 2297d7024fab
wine: created the configuration directory '/root/.wine'
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
err:ole:apartment_createwindowifneeded CreateWindow failed with error 183
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
err:ole:get_local_server_stream Failed: 80004002
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
err:ole:get_local_server_stream Failed: 800736b7
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
err:module:import_dll Loading library urlmon.dll (which is needed by L"C:\\windows\\system32\\mshtml.dll") failed (error c000007b).
wine: configuration in '/root/.wine' has been updated.
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
 ---> a051218b075e
Removing intermediate container 2297d7024fab
Step 55/57 : COPY tests/test.c tests/test-tors.c /build/test/
 ---> 092c0b481d75
Removing intermediate container 7c3fb0d7aea9
Step 56/57 : RUN cd test &&     for arch in $TOOLCHAIN_ARCHS; do         wine64 $CROSS_TOOLCHAIN_PREFIX-x86_64/bin/clang -target x86_64-windows-gnu test.c -o test-c-$arch.exe || exit 1;     done
 ---> Running in 747d763ec06f
fixme:file:FindFirstFileExW flags not implemented 0x00000002
fixme:file:FindFirstFileExW flags not implemented 0x00000002
fixme:file:FindFirstFileExW flags not implemented 0x00000002
fixme:file:FindFirstFileExW flags not implemented 0x00000002
LLVM ERROR: Could not acquire a cryptographic context: Unknown error (0x80090017)
The command '/bin/sh -c cd test &&     for arch in $TOOLCHAIN_ARCHS; do         wine64 $CROSS_TOOLCHAIN_PREFIX-x86_64/bin/clang -target x86_64-windows-gnu test.c -o test-c-$arch.exe || exit 1;     done' returned a non-zero code: 1
```

**Comment by martell** [comment]
There are notes about this error in the dockerfile.
I created an upstream bug report
https://bugs.winehq.org/show_bug.cgi?id=44699
then narrowed it down to the alpine package and created a PR.
https://github.com/alpinelinux/aports/pull/3576
Waiting for it to get merged.

You should just be able to extract the toolchains from `747d763ec06f` based on your log.

**Comment by ChrisChiasson** [comment]
This is probably a dumb question. Should I move my gcc executable to the cross-x86_64/bin directory after pulling the clang build onto my Windows desktop? I ask because clang++ doesn't seem to be able to find the standard library headers, but I am afraid to use the -target option because I want this clang to find and use its own headers.

**Comment by martell** [comment]
> This is probably a dumb question.

No such thing my friend. :)

This should only becomes an issue if `*-w64-mingw32-gcc.exe` or `mingw32-gcc.exe` is in your PATH. see here https://github.com/llvm-mirror/clang/blob/master/lib/Driver/ToolChains/MinGW.cpp#L298

I can add a patch that removes `findGcc()` locally if this is a big issue.
I have some cleanup commits lying around from last weekend and I intend to cleanup some stuff very shortly on this anyway.

> I ask because clang++ doesn't seem to be able to find the standard library headers

I will have a look at this over the weekend.
Now that we have a proper fix for wine this should be much easier to test.

Another thing I noticed was that the symlinks don't work when going from linux to windows so we should patch cmake to use cp instead of ls when doing the cross build.

We can also set LLVM_DEFAULT_TARGET but I believe that is not needed because it will default to windows-gnu regardless.

**Comment by ChrisChiasson** [comment]
I guess I am thinking about the reverse: leveraging the FindGcc() method
(that you mentioned) to force clang to find its own headers by moving gcc
into clang's bin folder. Would that be a dumb idea? Is there a better
method to make clang on Windows realize the includes are located off its
own folder rather than somewhere else? BTW, I wanted to say I very much
appreciate your help/responses. Otherwise I would be incredibly lost.

**Comment by martell** [comment]
> I guess I am thinking about the reverse: leveraging the FindGcc() method (that you mentioned) to force clang to find its own headers by moving gcc into clang's bin folder. Would that be a dumb idea? Is there a better method to make clang on Windows realize the includes are located off its own folder rather than somewhere else?

You can make a copy of clang.exe as gcc.exe in the same folder and that should have the same effect.
In general if there is no gcc in your PATH it should just work as is so there may be some c++ forlder not copied in the current toolchain.

Will find out in the next day or so  :)

**Comment by ChrisChiasson** [comment]
That is a very clever idea. Thank you. BTW, all I pulled out was the cross-x86_64 folder, so if the files are outside of that folder then... whoops. I did notice the symlink issue you posted above when I untarred the files, but it slipped my mind later. I also concur with you that clang uses the Windows target without needing the environment variable.

**Comment by lrmw** [comment]
Hi there, since the discussion is already about the built toolchain I thought I can ask the obvious question here @martell: Are you planning on providing binary snapshots of the native toolchain? I currently have no easy access to a Linux VM and would love to play around with it on Windows.

Thanks for this project! Putting it all together in a reliable/reproducible fashion is not at all easy but very neccessary.

**Comment by martell** [comment]
I'll start providing binary releases starting with the llvm 7.0.0 release.
